version: '3.8'

services:
  # Baza danych
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - default_net

  # Aplikacja RAG
  app:
    build: .
    depends_on:
      - db
    ports:
      - "8501:8501"
    environment:
      # Przekazujemy zmienne z .env do wnętrza kontenera Python
      DB_HOST: ${POSTGRES_HOST}
      DB_PORT: 5432
      DB_NAME: ${POSTGRES_DB}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      
      OLLAMA_BASE_URL: ${OLLAMA_BASE_URL}
      OLLAMA_MODEL: ${OLLAMA_MODEL_CHAT}
      OLLAMA_EMBED_MODEL: ${OLLAMA_MODEL_EMBED}
      
      HISTORY_DAYS: ${HISTORY_DAYS}
      RAG_K_RETRIEVAL: ${RAG_K_RETRIEVAL}
    networks:
      - default_net

volumes:
  postgres_data:

networks:
  default_net:
    name: ${AI_NETWORK_NAME} # Docker użyje nazwy z pliku .env
    external: true